# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'


pod 'AFNetworking', '~> 2.0'
pod 'Lockbox', '~> 2.0'

target 'MagicCardWall' do

end

target 'MagicCardWallTests' do

end

